using InovaSkill.Importer.Domain.Entities;
using InovaSkill.Importer.Domain.Enums;
using InovaSkill.Importer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Npgsql;

namespace InovaSkill.Importer.Infrastructure.Persistence.Bootstrap;

public static class DbSchemaBootstrapper
{
    public static async Task EnsureProgressColumnsAsync(DbContext db, CancellationToken cancellationToken = default)
    {
        if (db is not ImportDbContext context)
        {
            return;
        }

        await EnsureAppUsersTableAsync(context, cancellationToken);
    }

    private static async Task EnsureJobsTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "Jobs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Type" character varying(128) NOT NULL,
                "Status" integer NOT NULL,
                "ProgressPercent" integer NOT NULL,
                "CurrentStep" character varying(128) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "StartedAt" timestamp with time zone NULL,
                "FinishedAt" timestamp with time zone NULL,
                "UserId" character varying(128) NULL,
                "PayloadJson" jsonb NOT NULL,
                "ResultJson" jsonb NULL,
                "Error" character varying(4000) NOT NULL,
                "RetryCount" integer NOT NULL,
                "LockedBy" character varying(128) NOT NULL,
                "LockedAt" timestamp with time zone NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_Jobs_Status_CreatedAt"
            ON "Jobs" ("Status", "CreatedAt");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_Jobs_Type_Status_CreatedAt"
            ON "Jobs" ("Type", "Status", "CreatedAt");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_Jobs_LockedAt"
            ON "Jobs" ("LockedAt");
            """,
            cancellationToken);
    }

    private static async Task EnsureAppUsersTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "AppUsers" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" character varying(256) NOT NULL,
                "Email" character varying(256) NOT NULL,
                "Role" character varying(64) NOT NULL DEFAULT 'gestor',
                "PasswordHash" character varying(1024) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "AppUsers"
            ADD COLUMN IF NOT EXISTS "Role" character varying(64) NOT NULL DEFAULT 'gestor';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppUsers_Email"
            ON "AppUsers" ("Email");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppUsers_Name"
            ON "AppUsers" ("Name");
            """,
            cancellationToken);
    }

    private static async Task EnsureFileJobsColumnsAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "OriginalFileName" character varying(512) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "ImportFileTypeCode" character varying(64) NULL;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "StartedAt" timestamp with time zone NULL;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "FinishedAt" timestamp with time zone NULL;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "LockedBy" character varying(128) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "LockedAt" timestamp with time zone NULL;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_FileJobs_LockedAt"
            ON "FileJobs" ("LockedAt");
            """,
            cancellationToken);
    }

    private static async Task EnsureProcessingMonitoringTablesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ProcessingStepExecutions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FileJobId" bigint NOT NULL,
                "Step" character varying(64) NOT NULL,
                "StartedAt" timestamp with time zone NOT NULL,
                "FinishedAt" timestamp with time zone NULL,
                "Status" character varying(32) NOT NULL,
                "ProcessedRows" integer NOT NULL,
                "ErrorCount" integer NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ProcessingStepExecutions_FileJobId"
            ON "ProcessingStepExecutions" ("FileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ProcessingStepExecutions_Step_StartedAt"
            ON "ProcessingStepExecutions" ("Step", "StartedAt");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ProcessingJobLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FileJobId" bigint NOT NULL,
                "Timestamp" timestamp with time zone NOT NULL,
                "Stage" character varying(64) NOT NULL,
                "Level" character varying(32) NOT NULL,
                "Message" character varying(1024) NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ProcessingJobLogs_FileJobId_Timestamp"
            ON "ProcessingJobLogs" ("FileJobId", "Timestamp");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ProcessingJobEventLogs" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "FileJobId" bigint NOT NULL,
                "EventType" character varying(128) NOT NULL,
                "Status" character varying(32) NOT NULL,
                "CorrelationId" uuid NOT NULL,
                "RetryCount" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "ProcessedAt" timestamp with time zone NULL,
                "ErrorMessage" character varying(1024) NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ProcessingJobEventLogs_FileJobId_EventType_CorrelationId"
            ON "ProcessingJobEventLogs" ("FileJobId", "EventType", "CorrelationId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ProcessingJobEventLogs_Status_CreatedAt"
            ON "ProcessingJobEventLogs" ("Status", "CreatedAt");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "WorkerHeartbeats" (
                "WorkerId" character varying(128) PRIMARY KEY,
                "LastSeenAt" timestamp with time zone NOT NULL,
                "ProcessedJobsToday" integer NOT NULL,
                "IdleSinceAt" timestamp with time zone NULL,
                "CurrentJobId" bigint NULL,
                "CurrentTask" character varying(128) NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_WorkerHeartbeats_LastSeenAt"
            ON "WorkerHeartbeats" ("LastSeenAt");
            """,
            cancellationToken);
    }

    private static async Task EnsureCommercialTransactionsTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "CommercialTransactions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DocumentNumber" character varying(64) NOT NULL,
                "TransactionDate" timestamp with time zone NOT NULL,
                "CustomerCode" character varying(64) NOT NULL,
                "CustomerName" character varying(256) NOT NULL,
                "SupplierCode" character varying(64) NOT NULL DEFAULT '',
                "SupplierName" character varying(256) NOT NULL DEFAULT '',
                "RouteName" character varying(256) NOT NULL DEFAULT '',
                "ProductCode" character varying(64) NOT NULL,
                "ProductDescription" character varying(512) NOT NULL,
                "Quantity" numeric(18,3) NOT NULL,
                "UnitPrice" numeric(18,2) NOT NULL,
                "TotalAmount" numeric(18,2) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "GrossWeightKg" numeric(18,3) NOT NULL,
                "SourceFileJobId" bigint NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "CommercialTransactions"
            ADD COLUMN IF NOT EXISTS "SupplierCode" character varying(64) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "CommercialTransactions"
            ADD COLUMN IF NOT EXISTS "SupplierName" character varying(256) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "CommercialTransactions"
            ADD COLUMN IF NOT EXISTS "RouteName" character varying(256) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_DocumentNumber"
            ON "CommercialTransactions" ("DocumentNumber");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_SourceFileJobId"
            ON "CommercialTransactions" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_TransactionDate"
            ON "CommercialTransactions" ("TransactionDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_CustomerName"
            ON "CommercialTransactions" ("CustomerName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_SupplierName"
            ON "CommercialTransactions" ("SupplierName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_RouteName"
            ON "CommercialTransactions" ("RouteName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_ProductCode"
            ON "CommercialTransactions" ("ProductCode");
            """,
            cancellationToken);

        await ExecuteCreateIndexIgnoringDuplicateAsync(
            db,
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_ProductDescription"
            ON "CommercialTransactions" ("ProductDescription");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_City"
            ON "CommercialTransactions" ("City");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_SourceFileJobId_TransactionDate"
            ON "CommercialTransactions" ("SourceFileJobId", "TransactionDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DELETE FROM "CommercialTransactions" c
            USING "CommercialTransactions" d
            WHERE c."Id" > d."Id"
              AND c."DocumentNumber" = d."DocumentNumber"
              AND c."TransactionDate" = d."TransactionDate"
              AND c."CustomerCode" = d."CustomerCode"
              AND c."ProductCode" = d."ProductCode"
              AND c."TransactionType" = d."TransactionType"
              AND c."City" = d."City"
              AND c."ProductGroup" = d."ProductGroup"
              AND c."Quantity" = d."Quantity"
              AND c."UnitPrice" = d."UnitPrice"
              AND c."GrossWeightKg" = d."GrossWeightKg";
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "UQ_CommercialTransactions_BusinessKey"
            ON "CommercialTransactions"
            ("DocumentNumber", "TransactionDate", "CustomerCode", "ProductCode", "TransactionType", "City", "ProductGroup", "Quantity", "UnitPrice", "GrossWeightKg");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "CommercialTransactions"
            ALTER COLUMN "Quantity" TYPE numeric(18,3) USING "Quantity"::numeric;
            """,
            cancellationToken);
    }

    private static async Task EnsureRoutePlanningTablesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "RoutePlanningImports" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "SourceFileName" character varying(512) NOT NULL,
                "ImportedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "RoutePlanningImports"
            ADD COLUMN IF NOT EXISTS "SourceFileJobId" bigint NOT NULL DEFAULT 0;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "RoutePlanningImports"
            ADD COLUMN IF NOT EXISTS "SourceFileName" character varying(512) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "RoutePlanningImports"
            ADD COLUMN IF NOT EXISTS "ImportedAt" timestamp with time zone NOT NULL DEFAULT NOW();
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RoutePlanningImports_SourceFileJobId"
            ON "RoutePlanningImports" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_RoutePlanningImports_ImportedAt"
            ON "RoutePlanningImports" ("ImportedAt");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "RoutePlans" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RoutePlanningImportId" bigint NOT NULL,
                "SheetName" character varying(128) NOT NULL,
                "WeekdayLabel" character varying(64) NOT NULL,
                "WeekdayOrder" integer NOT NULL,
                "RouteOrder" integer NOT NULL,
                "RouteName" character varying(256) NOT NULL,
                "VehicleType" character varying(64) NOT NULL,
                "VehicleCapacityKg" numeric(18,2) NULL,
                "TotalDeliveries" integer NULL,
                "TotalAverageLoadKg" numeric(18,3) NULL,
                "OccupancyPercent" numeric(9,2) NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_RoutePlans_Import_Weekday_RouteOrder"
            ON "RoutePlans" ("RoutePlanningImportId", "WeekdayOrder", "RouteOrder");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_RoutePlans_Weekday_RouteName"
            ON "RoutePlans" ("WeekdayOrder", "RouteName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_RoutePlans_RoutePlanningImports_RoutePlanningImportId'
                ) THEN
                    ALTER TABLE "RoutePlans"
                    ADD CONSTRAINT "FK_RoutePlans_RoutePlanningImports_RoutePlanningImportId"
                    FOREIGN KEY ("RoutePlanningImportId") REFERENCES "RoutePlanningImports" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "RouteStops" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RoutePlanId" bigint NOT NULL,
                "StopOrder" integer NOT NULL,
                "DestinationName" character varying(256) NOT NULL,
                "DeliveriesRaw" character varying(64) NOT NULL,
                "DeliveriesCount" integer NULL,
                "AverageLoadKg" numeric(18,3) NULL,
                "Note" character varying(2000) NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_RouteStops_RoutePlanId_StopOrder"
            ON "RouteStops" ("RoutePlanId", "StopOrder");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_RouteStops_DestinationName"
            ON "RouteStops" ("DestinationName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_RouteStops_RoutePlans_RoutePlanId'
                ) THEN
                    ALTER TABLE "RouteStops"
                    ADD CONSTRAINT "FK_RouteStops_RoutePlans_RoutePlanId"
                    FOREIGN KEY ("RoutePlanId") REFERENCES "RoutePlans" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "TruckCapacityProfiles" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "RoutePlanningImportId" bigint NOT NULL,
                "VehicleType" character varying(64) NOT NULL,
                "CapacityKg" numeric(18,2) NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_TruckCapacityProfiles_Import_VehicleType"
            ON "TruckCapacityProfiles" ("RoutePlanningImportId", "VehicleType");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_TruckCapacityProfiles_RoutePlanningImports_RoutePlanningImportId'
                ) THEN
                    ALTER TABLE "TruckCapacityProfiles"
                    ADD CONSTRAINT "FK_TruckCapacityProfiles_RoutePlanningImports_RoutePlanningImportId"
                    FOREIGN KEY ("RoutePlanningImportId") REFERENCES "RoutePlanningImports" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            cancellationToken);
    }

    private static async Task EnsureImportFileTypesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ImportFileTypes" (
                "Id" uuid PRIMARY KEY,
                "Code" character varying(64) NOT NULL,
                "Name" character varying(256) NOT NULL,
                "Description" character varying(2000) NOT NULL,
                "AllowedExtensions" character varying(256) NOT NULL,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ImportFileTypes_Code"
            ON "ImportFileTypes" ("Code");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportFileTypes_IsActive"
            ON "ImportFileTypes" ("IsActive");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            INSERT INTO "ImportFileTypes" ("Id", "Code", "Name", "Description", "AllowedExtensions", "IsActive", "CreatedAt", "UpdatedAt")
            VALUES
            ('11111111-1111-1111-1111-111111111111', 'SALES_INVOICE', 'Nota Fiscal de Venda', 'Importacao de notas fiscais de venda', '.csv,.xlsx', true, NOW(), NOW()),
            ('22222222-2222-2222-2222-222222222222', 'CUSTOMER_LIST', 'Clientes', 'Importacao da tabela de clientes', '.csv,.xlsx', true, NOW(), NOW()),
            ('33333333-3333-3333-3333-333333333333', 'PRODUCT_LIST', 'Produtos', 'Importacao da tabela de produtos', '.csv,.xlsx', true, NOW(), NOW()),
            ('44444444-4444-4444-4444-444444444444', 'FINANCIAL_ENTRY', 'Lancamento Financeiro', 'Importacao de pedidos/lancamentos', '.csv,.xlsx', true, NOW(), NOW()),
            ('55555555-5555-5555-5555-555555555555', 'ROUTE_PLANNING', 'Rotas por Cidade', 'Importacao de planejamento de rotas por cidade e dia', '.xlsx', true, NOW(), NOW())
            ON CONFLICT ("Code") DO NOTHING;
            """,
            cancellationToken);
    }

    private static async Task EnsureSalesSummariesDailyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "SalesSummariesDaily" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "ReferenceDate" timestamp with time zone NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "TransactionCount" integer NOT NULL,
                "TotalQuantity" numeric(18,3) NOT NULL,
                "TotalAmount" numeric(18,2) NOT NULL,
                "TotalGrossWeightKg" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_SourceFileJobId"
            ON "SalesSummariesDaily" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_ReferenceDate"
            ON "SalesSummariesDaily" ("ReferenceDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_ReferenceDate_City_ProductGroup_TransactionType"
            ON "SalesSummariesDaily" ("ReferenceDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_SourceFileJobId_Date_City_Group_Type"
            ON "SalesSummariesDaily" ("SourceFileJobId", "ReferenceDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);
    }

    private static async Task EnsureSalesSummariesWeeklyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "SalesSummariesWeekly" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "WeekStartDate" timestamp with time zone NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "TransactionCount" integer NOT NULL,
                "TotalQuantity" numeric(18,3) NOT NULL,
                "TotalAmount" numeric(18,2) NOT NULL,
                "TotalGrossWeightKg" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_SourceFileJobId"
            ON "SalesSummariesWeekly" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_WeekStartDate"
            ON "SalesSummariesWeekly" ("WeekStartDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_WeekStartDate_City_ProductGroup_TransactionType"
            ON "SalesSummariesWeekly" ("WeekStartDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_SourceFileJobId_Week_City_Group_Type"
            ON "SalesSummariesWeekly" ("SourceFileJobId", "WeekStartDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);
    }

    private static async Task EnsureImportErrorsColumnsAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "ImportErrors"
            ADD COLUMN IF NOT EXISTS "Stage" character varying(64) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportErrors_FileJobId_Stage"
            ON "ImportErrors" ("FileJobId", "Stage");
            """,
            cancellationToken);
    }

    private static async Task EnsureCustomersColumnsAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "Customers"
            ADD COLUMN IF NOT EXISTS "CustomerCode" character varying(64) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_Customers_CustomerCode"
            ON "Customers" ("CustomerCode");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DELETE FROM "Customers" c
            USING "Customers" d
            WHERE c."Id" > d."Id"
              AND c."CustomerCode" = d."CustomerCode";
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Customers_CustomerCode"
            ON "Customers" ("CustomerCode");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DELETE FROM "Products" p
            USING "Products" d
            WHERE p."Id" > d."Id"
              AND p."Sku" = d."Sku";
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Products_Sku"
            ON "Products" ("Sku");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DELETE FROM "Orders" o
            USING "Orders" d
            WHERE o."Id" > d."Id"
              AND o."OrderNumber" = d."OrderNumber"
              AND o."CustomerEmail" = d."CustomerEmail"
              AND o."ProductSku" = d."ProductSku"
              AND o."OrderedAt" = d."OrderedAt";
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Orders_BusinessKey"
            ON "Orders" ("OrderNumber", "CustomerEmail", "ProductSku", "OrderedAt");
            """,
            cancellationToken);
    }

    private static async Task EnsureCustomerSummariesDailyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "CustomerSummariesDaily" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "ReferenceDate" timestamp with time zone NOT NULL,
                "CustomerCode" character varying(64) NOT NULL,
                "CustomerName" character varying(256) NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "Orders" integer NOT NULL,
                "Revenue" numeric(18,2) NOT NULL,
                "Quantity" numeric(18,3) NOT NULL,
                "Weight" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_SourceFileJobId" ON "CustomerSummariesDaily" ("SourceFileJobId");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_ReferenceDate" ON "CustomerSummariesDaily" ("ReferenceDate");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_CustomerName" ON "CustomerSummariesDaily" ("CustomerName");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_ReferenceDate_CustomerName" ON "CustomerSummariesDaily" ("ReferenceDate", "CustomerName");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_UQ_BySourceAndDimensions" ON "CustomerSummariesDaily" ("SourceFileJobId", "ReferenceDate", "CustomerCode", "City", "ProductGroup", "TransactionType");""", cancellationToken);
    }

    private static async Task EnsureCustomerSummariesWeeklyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "CustomerSummariesWeekly" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "WeekStartDate" timestamp with time zone NOT NULL,
                "CustomerCode" character varying(64) NOT NULL,
                "CustomerName" character varying(256) NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "Orders" integer NOT NULL,
                "Revenue" numeric(18,2) NOT NULL,
                "Quantity" numeric(18,3) NOT NULL,
                "Weight" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_SourceFileJobId" ON "CustomerSummariesWeekly" ("SourceFileJobId");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_WeekStartDate" ON "CustomerSummariesWeekly" ("WeekStartDate");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_CustomerName" ON "CustomerSummariesWeekly" ("CustomerName");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_WeekStartDate_CustomerName" ON "CustomerSummariesWeekly" ("WeekStartDate", "CustomerName");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_UQ_BySourceAndDimensions" ON "CustomerSummariesWeekly" ("SourceFileJobId", "WeekStartDate", "CustomerCode", "City", "ProductGroup", "TransactionType");""", cancellationToken);
    }

    private static async Task EnsureCustomerSummariesMonthlyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "CustomerSummariesMonthly" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "MonthStartDate" timestamp with time zone NOT NULL,
                "CustomerCode" character varying(64) NOT NULL,
                "CustomerName" character varying(256) NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "Orders" integer NOT NULL,
                "Revenue" numeric(18,2) NOT NULL,
                "Quantity" numeric(18,3) NOT NULL,
                "Weight" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_SourceFileJobId" ON "CustomerSummariesMonthly" ("SourceFileJobId");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_MonthStartDate" ON "CustomerSummariesMonthly" ("MonthStartDate");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_CustomerName" ON "CustomerSummariesMonthly" ("CustomerName");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_MonthStartDate_CustomerName" ON "CustomerSummariesMonthly" ("MonthStartDate", "CustomerName");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_UQ_BySourceAndDimensions" ON "CustomerSummariesMonthly" ("SourceFileJobId", "MonthStartDate", "CustomerCode", "City", "ProductGroup", "TransactionType");""", cancellationToken);
    }

    private static async Task EnsureClienteIndicadoresTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ClienteIndicadores" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ClienteId" character varying(64) NOT NULL,
                "Faturamento3M" numeric(18,2) NOT NULL,
                "Faturamento6M" numeric(18,2) NOT NULL,
                "Faturamento12M" numeric(18,2) NOT NULL,
                "Crescimento3M" numeric(9,2) NULL,
                "Crescimento6M" numeric(9,2) NULL,
                "Crescimento12M" numeric(9,2) NULL,
                "MediaMovel3M" numeric(18,2) NOT NULL,
                "MediaMovel6M" numeric(18,2) NOT NULL,
                "MediaMovel12M" numeric(18,2) NOT NULL,
                "FrequenciaCompra" numeric(18,2) NOT NULL,
                "TicketMedioGeral" numeric(18,2) NOT NULL,
                "ScoreCrescimento" integer NOT NULL,
                "ScoreFrequencia" integer NOT NULL,
                "ScoreTicket" integer NOT NULL,
                "ScoreRecencia" integer NOT NULL,
                "ScorePotencial" integer NOT NULL,
                "Tendencia" character varying(64) NOT NULL,
                "Classificacao" character varying(16) NOT NULL,
                "AtualizadoEm" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_ClienteIndicadores_ClienteId" ON "ClienteIndicadores" ("ClienteId");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_ClienteIndicadores_ScorePotencial" ON "ClienteIndicadores" ("ScorePotencial");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_ClienteIndicadores_Tendencia" ON "ClienteIndicadores" ("Tendencia");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_ClienteIndicadores_Classificacao" ON "ClienteIndicadores" ("Classificacao");""", cancellationToken);
    }

    private static async Task EnsureClienteForecastsTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ClienteForecasts" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ClienteId" character varying(64) NOT NULL,
                "Previsao30Dias" numeric(18,2) NOT NULL,
                "Previsao60Dias" numeric(18,2) NOT NULL,
                "Previsao90Dias" numeric(18,2) NOT NULL,
                "TendenciaPrevista" character varying(64) NOT NULL,
                "ErroMedioHistorico" numeric(18,2) NULL,
                "ConfiancaModelo" numeric(9,2) NULL,
                "UltimaObservacao" timestamp with time zone NOT NULL,
                "AtualizadoEm" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "ClienteForecasts"
            ADD COLUMN IF NOT EXISTS "UltimaObservacao" timestamp with time zone NOT NULL DEFAULT NOW();
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync("""CREATE UNIQUE INDEX IF NOT EXISTS "IX_ClienteForecasts_ClienteId" ON "ClienteForecasts" ("ClienteId");""", cancellationToken);
        await db.Database.ExecuteSqlRawAsync("""CREATE INDEX IF NOT EXISTS "IX_ClienteForecasts_TendenciaPrevista" ON "ClienteForecasts" ("TendenciaPrevista");""", cancellationToken);
    }

    private static async Task EnsureImportTemplateV2TablesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "TransformRules" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" character varying(64) NOT NULL,
                "Name" character varying(128) NOT NULL,
                "Description" character varying(2000) NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT true
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_TransformRules_Code"
            ON "TransformRules" ("Code");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ImportTemplatesV2" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ImportFileTypeId" uuid NULL,
                "Name" character varying(256) NOT NULL,
                "Description" character varying(2000) NOT NULL,
                "IsActive" boolean NOT NULL,
                "FileNamePattern" character varying(256) NOT NULL,
                "RequiredHeadersCsv" character varying(2048) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportTemplatesV2_IsActive"
            ON "ImportTemplatesV2" ("IsActive");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportTemplatesV2_ImportFileTypeId"
            ON "ImportTemplatesV2" ("ImportFileTypeId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_ImportTemplatesV2_ImportFileTypes_ImportFileTypeId'
                ) THEN
                    ALTER TABLE "ImportTemplatesV2"
                    ADD CONSTRAINT "FK_ImportTemplatesV2_ImportFileTypes_ImportFileTypeId"
                    FOREIGN KEY ("ImportFileTypeId") REFERENCES "ImportFileTypes" ("Id") ON DELETE RESTRICT;
                END IF;
            END $$;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ImportColumnMappings" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ImportTemplateId" bigint NOT NULL,
                "SourceColumnName" character varying(256) NOT NULL,
                "TargetFieldName" character varying(256) NOT NULL,
                "IsRequired" boolean NOT NULL,
                "DefaultValue" character varying(4000) NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportColumnMappings_ImportTemplateId_TargetFieldName"
            ON "ImportColumnMappings" ("ImportTemplateId", "TargetFieldName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_ImportColumnMappings_ImportTemplatesV2_ImportTemplateId'
                ) THEN
                    ALTER TABLE "ImportColumnMappings"
                    ADD CONSTRAINT "FK_ImportColumnMappings_ImportTemplatesV2_ImportTemplateId"
                    FOREIGN KEY ("ImportTemplateId") REFERENCES "ImportTemplatesV2" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ColumnMappingTransformRules" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ImportColumnMappingId" bigint NOT NULL,
                "TransformRuleId" bigint NOT NULL,
                "Order" integer NOT NULL,
                "ParametersJson" jsonb NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ColumnMappingTransformRules_ImportColumnMappingId_Order"
            ON "ColumnMappingTransformRules" ("ImportColumnMappingId", "Order");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ColumnMappingTransformRules_TransformRuleId"
            ON "ColumnMappingTransformRules" ("TransformRuleId");
            """,
            cancellationToken);
    }

    private static async Task ExecuteCreateIndexIgnoringDuplicateAsync(
        ImportDbContext db,
        string sql,
        CancellationToken cancellationToken)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync(sql, cancellationToken);
        }
        catch (PostgresException ex) when (ex.SqlState == PostgresErrorCodes.UniqueViolation)
        {
            // Two local processes can bootstrap together; the index exists after the concurrent winner commits.
        }
    }
}
