using InovaSkill.Importer.Domain.Entities;
using InovaSkill.Importer.Domain.Enums;
using InovaSkill.Importer.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;

namespace InovaSkill.Importer.Infrastructure.Persistence.Bootstrap;

public static class DbSchemaBootstrapper
{
    public static async Task EnsureProgressColumnsAsync(DbContext db, CancellationToken cancellationToken = default)
    {
        if (db is not ImportDbContext context)
        {
            return;
        }

        await EnsureFileJobsColumnsAsync(context, cancellationToken);
        await EnsureCommercialTransactionsTableAsync(context, cancellationToken);
        await EnsureSalesSummariesDailyTableAsync(context, cancellationToken);
        await EnsureSalesSummariesWeeklyTableAsync(context, cancellationToken);
        await EnsureImportFileTypesAsync(context, cancellationToken);
        await EnsureImportTemplateV2TablesAsync(context, cancellationToken);
        await EnsureDefaultTemplatesAsync(context, cancellationToken);
        await EnsureTransformRulesCatalogAsync(context, cancellationToken);
        await EnsureSalesInvoiceTemplateV2Async(context, cancellationToken);
    }

    private static async Task EnsureFileJobsColumnsAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "OriginalFileName" character varying(512) NOT NULL DEFAULT '';
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "FileJobs"
            ADD COLUMN IF NOT EXISTS "ImportFileTypeCode" character varying(64) NULL;
            """,
            cancellationToken);
    }

    private static async Task EnsureCommercialTransactionsTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "CommercialTransactions" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "DocumentNumber" character varying(64) NOT NULL,
                "TransactionDate" timestamp with time zone NOT NULL,
                "CustomerCode" character varying(64) NOT NULL,
                "CustomerName" character varying(256) NOT NULL,
                "ProductCode" character varying(64) NOT NULL,
                "ProductDescription" character varying(512) NOT NULL,
                "Quantity" numeric(18,3) NOT NULL,
                "UnitPrice" numeric(18,2) NOT NULL,
                "TotalAmount" numeric(18,2) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "GrossWeightKg" numeric(18,3) NOT NULL,
                "SourceFileJobId" bigint NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_DocumentNumber"
            ON "CommercialTransactions" ("DocumentNumber");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_SourceFileJobId"
            ON "CommercialTransactions" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_TransactionDate"
            ON "CommercialTransactions" ("TransactionDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_CustomerName"
            ON "CommercialTransactions" ("CustomerName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_ProductCode"
            ON "CommercialTransactions" ("ProductCode");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_City"
            ON "CommercialTransactions" ("City");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_SourceFileJobId_TransactionDate"
            ON "CommercialTransactions" ("SourceFileJobId", "TransactionDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            ALTER TABLE "CommercialTransactions"
            ALTER COLUMN "Quantity" TYPE numeric(18,3) USING "Quantity"::numeric;
            """,
            cancellationToken);
    }

    private static async Task EnsureImportFileTypesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ImportFileTypes" (
                "Id" uuid PRIMARY KEY,
                "Code" character varying(64) NOT NULL,
                "Name" character varying(256) NOT NULL,
                "Description" character varying(2000) NOT NULL,
                "AllowedExtensions" character varying(256) NOT NULL,
                "IsActive" boolean NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ImportFileTypes_Code"
            ON "ImportFileTypes" ("Code");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportFileTypes_IsActive"
            ON "ImportFileTypes" ("IsActive");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            INSERT INTO "ImportFileTypes" ("Id", "Code", "Name", "Description", "AllowedExtensions", "IsActive", "CreatedAt", "UpdatedAt")
            VALUES
            ('11111111-1111-1111-1111-111111111111', 'SALES_INVOICE', 'Nota Fiscal de Venda', 'Importacao de notas fiscais de venda', '.csv,.xlsx', true, NOW(), NOW()),
            ('22222222-2222-2222-2222-222222222222', 'CUSTOMER_LIST', 'Lista de Clientes', 'Importacao de cadastros de clientes', '.csv,.xlsx', true, NOW(), NOW()),
            ('33333333-3333-3333-3333-333333333333', 'PRODUCT_LIST', 'Lista de Produtos', 'Importacao de catalogo de produtos', '.csv,.xlsx', true, NOW(), NOW()),
            ('44444444-4444-4444-4444-444444444444', 'FINANCIAL_ENTRY', 'Lancamento Financeiro', 'Importacao de pedidos/lancamentos', '.csv,.xlsx', true, NOW(), NOW())
            ON CONFLICT ("Code") DO NOTHING;
            """,
            cancellationToken);
    }

    private static async Task EnsureSalesSummariesDailyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "SalesSummariesDaily" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "ReferenceDate" timestamp with time zone NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "TransactionCount" integer NOT NULL,
                "TotalQuantity" numeric(18,3) NOT NULL,
                "TotalAmount" numeric(18,2) NOT NULL,
                "TotalGrossWeightKg" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_SourceFileJobId"
            ON "SalesSummariesDaily" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_ReferenceDate"
            ON "SalesSummariesDaily" ("ReferenceDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_ReferenceDate_City_ProductGroup_TransactionType"
            ON "SalesSummariesDaily" ("ReferenceDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_SourceFileJobId_Date_City_Group_Type"
            ON "SalesSummariesDaily" ("SourceFileJobId", "ReferenceDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);
    }

    private static async Task EnsureSalesSummariesWeeklyTableAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "SalesSummariesWeekly" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "SourceFileJobId" bigint NOT NULL,
                "WeekStartDate" timestamp with time zone NOT NULL,
                "City" character varying(256) NOT NULL,
                "ProductGroup" character varying(128) NOT NULL,
                "TransactionType" character varying(128) NOT NULL,
                "TransactionCount" integer NOT NULL,
                "TotalQuantity" numeric(18,3) NOT NULL,
                "TotalAmount" numeric(18,2) NOT NULL,
                "TotalGrossWeightKg" numeric(18,3) NOT NULL,
                "ProcessedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_SourceFileJobId"
            ON "SalesSummariesWeekly" ("SourceFileJobId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_WeekStartDate"
            ON "SalesSummariesWeekly" ("WeekStartDate");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_WeekStartDate_City_ProductGroup_TransactionType"
            ON "SalesSummariesWeekly" ("WeekStartDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_SourceFileJobId_Week_City_Group_Type"
            ON "SalesSummariesWeekly" ("SourceFileJobId", "WeekStartDate", "City", "ProductGroup", "TransactionType");
            """,
            cancellationToken);
    }

    private static async Task EnsureDefaultTemplatesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        var templates = await db.PreProcessorTemplates
            .Include(x => x.Rules)
            .ToListAsync(cancellationToken);

        var products = UpsertTemplate(
            db,
            templates,
            "default_products_v1",
            "Template Padrão Products",
            FileType.Products,
            "products",
            "sku,name,price");

        var orders = UpsertTemplate(
            db,
            templates,
            "default_orders_v1",
            "Template Padrão Orders",
            FileType.Orders,
            "orders",
            "ordernumber,customeremail,productsku,quantity,orderdate");

        var customers = UpsertTemplate(
            db,
            templates,
            "default_customers_v1",
            "Template Padrão Customers",
            FileType.Customers,
            "customers",
            "name,email");

        var commercialTransactions = UpsertTemplate(
            db,
            templates,
            "default_commercial_transactions_v1",
            "Template Padrão Vendas",
            FileType.CommercialTransaction,
            "vendas",
            "documentnumber,transactiondate,customercode,customername,productcode,productdescription,quantity,unitprice,totalamount,transactiontype,city,productgroup,grossweightkg");
        commercialTransactions.ColumnMappingsJson = """
        [
          { "From": "documento", "To": "documentnumber" },
          { "From": "data", "To": "transactiondate" },
          { "From": "cliente", "To": "customercode" },
          { "From": "nome", "To": "customername" },
          { "From": "produto", "To": "productcode" },
          { "From": "descricao", "To": "productdescription" },
          { "From": "quantidade", "To": "quantity" },
          { "From": "vlr. unit.", "To": "unitprice" },
          { "From": "total", "To": "totalamount" },
          { "From": "tipo", "To": "transactiontype" },
          { "From": "tipo operacao descricao", "To": "transactiontype" },
          { "From": "tipo operacao", "To": "transactiontype" },
          { "From": "cidade", "To": "city" },
          { "From": "grupo descricao", "To": "productgroup" },
          { "From": "grupo descrica", "To": "productgroup" },
          { "From": "grupo prod.", "To": "productgroup" },
          { "From": "peso bruto(kg)", "To": "grossweightkg" }
        ]
        """;

        UpsertRule(products, "products_extract_weight_value", "extract_regex", true, "{\"source\":\"description\",\"target\":\"weight_value\",\"pattern\":\"(\\\\d+([.,]\\\\d+)?)\\\\s*(kg|g)\",\"group\":\"1\",\"overwrite\":false}", 10);
        UpsertRule(products, "products_extract_weight_unit", "extract_regex", true, "{\"source\":\"description\",\"target\":\"weight_unit\",\"pattern\":\"(\\\\d+([.,]\\\\d+)?)\\\\s*(kg|g)\",\"group\":\"3\",\"overwrite\":false}", 20);
        UpsertRule(products, "products_normalize_weight_value", "normalize_number", true, "{\"column\":\"weight_value\",\"target\":\"weight_value\",\"decimalSeparator\":\",\",\"thousandSeparator\":\".\"}", 30);
        UpsertRule(products, "products_normalize_price", "normalize_number", true, "{\"column\":\"price\",\"target\":\"price\",\"decimalSeparator\":\",\",\"thousandSeparator\":\".\"}", 40);
        UpsertRule(products, "products_convert_weight_kg", "convert_weight_to_kg", true, "{\"valueColumn\":\"weight_value\",\"unitColumn\":\"weight_unit\",\"target\":\"weight_kg\"}", 45);
        UpsertRule(products, "products_validate_required_sku", "validate_required", true, "{\"column\":\"sku\",\"message\":\"sku obrigatório\"}", 100);
        UpsertRule(products, "products_validate_required_name", "validate_required", true, "{\"column\":\"name\",\"message\":\"name obrigatório\"}", 110);
        UpsertRule(products, "products_validate_decimal_price", "validate_decimal", true, "{\"column\":\"price\",\"message\":\"price inválido\"}", 120);

        UpsertRule(orders, "orders_map_orderdate_orderedat", "map_column", true, "{\"from\":\"orderdate\",\"to\":\"orderedat\",\"overwrite\":false}", 5);
        UpsertRule(orders, "orders_normalize_orderdate", "normalize_date", true, "{\"column\":\"orderedat\",\"target\":\"orderedat\",\"formats\":[\"dd/MM/yyyy\",\"yyyy-MM-dd\",\"MM/dd/yyyy\"],\"outputFormat\":\"yyyy-MM-dd\"}", 10);
        UpsertRule(orders, "orders_normalize_quantity", "normalize_number", true, "{\"column\":\"quantity\",\"target\":\"quantity\",\"decimalSeparator\":\",\",\"thousandSeparator\":\".\"}", 20);
        UpsertRule(orders, "orders_validate_required_ordernumber", "validate_required", true, "{\"column\":\"ordernumber\",\"message\":\"ordernumber obrigatório\"}", 100);
        UpsertRule(orders, "orders_validate_email_customer", "validate_email", true, "{\"column\":\"customeremail\",\"message\":\"customeremail inválido\"}", 110);
        UpsertRule(orders, "orders_validate_int_quantity", "validate_int", true, "{\"column\":\"quantity\",\"message\":\"quantity inválido\"}", 120);
        UpsertRule(orders, "orders_validate_datetime_orderedat", "validate_datetime", true, "{\"column\":\"orderedat\",\"message\":\"orderedat inválido\"}", 130);

        UpsertRule(customers, "customers_split_single_column", "split_single_column", true, "{\"column\":\"raw\",\"delimiter\":\";\",\"headers\":[\"name\",\"email\",\"createdat\"],\"overwrite\":false}", 10);
        UpsertRule(customers, "customers_map_email_alias", "map_column", true, "{\"from\":\"e-mail\",\"to\":\"email\",\"overwrite\":false}", 20);
        UpsertRule(customers, "customers_validate_required_name", "validate_required", true, "{\"column\":\"name\",\"message\":\"name obrigatório\"}", 100);
        UpsertRule(customers, "customers_validate_email", "validate_email", true, "{\"column\":\"email\",\"message\":\"email inválido\"}", 110);

        UpsertRule(commercialTransactions, "sales_validate_required_documentnumber", "validate_required", true, "{\"column\":\"documentnumber\",\"message\":\"documentnumber obrigatório\"}", 100);
        UpsertRule(commercialTransactions, "sales_normalize_transactiondate", "normalize_date", true, "{\"column\":\"data\",\"target\":\"transactiondate\",\"formats\":[\"yyyyMMdd\",\"dd/MM/yyyy\",\"yyyy-MM-dd\",\"MM/dd/yyyy\"],\"outputFormat\":\"yyyy-MM-dd\"}", 10);
        UpsertRule(commercialTransactions, "sales_validate_datetime_transactiondate", "validate_datetime", true, "{\"column\":\"transactiondate\",\"message\":\"transactiondate inválido\"}", 110);
        UpsertRule(commercialTransactions, "sales_validate_decimal_quantity", "validate_decimal", true, "{\"column\":\"quantity\",\"message\":\"quantity inválido\"}", 120);
        UpsertRule(commercialTransactions, "sales_validate_decimal_unitprice", "validate_decimal", true, "{\"column\":\"unitprice\",\"message\":\"unitprice inválido\"}", 130);
        UpsertRule(commercialTransactions, "sales_validate_decimal_totalamount", "validate_decimal", true, "{\"column\":\"totalamount\",\"message\":\"totalamount inválido\"}", 140);
        UpsertRule(commercialTransactions, "sales_validate_decimal_grossweightkg", "validate_decimal", true, "{\"column\":\"grossweightkg\",\"message\":\"grossweightkg inválido\"}", 150);
        var legacyQuantityIntRule = commercialTransactions.Rules.FirstOrDefault(x => x.Name == "sales_validate_int_quantity");
        if (legacyQuantityIntRule is not null)
        {
            legacyQuantityIntRule.IsEnabled = false;
        }

        await db.SaveChangesAsync(cancellationToken);
    }

    private static async Task EnsureImportTemplateV2TablesAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "TransformRules" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" character varying(64) NOT NULL,
                "Name" character varying(128) NOT NULL,
                "Description" character varying(2000) NOT NULL,
                "IsActive" boolean NOT NULL DEFAULT true
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_TransformRules_Code"
            ON "TransformRules" ("Code");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ImportTemplatesV2" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ImportFileTypeId" uuid NULL,
                "Name" character varying(256) NOT NULL,
                "Description" character varying(2000) NOT NULL,
                "IsActive" boolean NOT NULL,
                "FileNamePattern" character varying(256) NOT NULL,
                "RequiredHeadersCsv" character varying(2048) NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportTemplatesV2_IsActive"
            ON "ImportTemplatesV2" ("IsActive");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportTemplatesV2_ImportFileTypeId"
            ON "ImportTemplatesV2" ("ImportFileTypeId");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_ImportTemplatesV2_ImportFileTypes_ImportFileTypeId'
                ) THEN
                    ALTER TABLE "ImportTemplatesV2"
                    ADD CONSTRAINT "FK_ImportTemplatesV2_ImportFileTypes_ImportFileTypeId"
                    FOREIGN KEY ("ImportFileTypeId") REFERENCES "ImportFileTypes" ("Id") ON DELETE RESTRICT;
                END IF;
            END $$;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ImportColumnMappings" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ImportTemplateId" bigint NOT NULL,
                "SourceColumnName" character varying(256) NOT NULL,
                "TargetFieldName" character varying(256) NOT NULL,
                "IsRequired" boolean NOT NULL,
                "DefaultValue" character varying(4000) NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ImportColumnMappings_ImportTemplateId_TargetFieldName"
            ON "ImportColumnMappings" ("ImportTemplateId", "TargetFieldName");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1
                    FROM pg_constraint
                    WHERE conname = 'FK_ImportColumnMappings_ImportTemplatesV2_ImportTemplateId'
                ) THEN
                    ALTER TABLE "ImportColumnMappings"
                    ADD CONSTRAINT "FK_ImportColumnMappings_ImportTemplatesV2_ImportTemplateId"
                    FOREIGN KEY ("ImportTemplateId") REFERENCES "ImportTemplatesV2" ("Id") ON DELETE CASCADE;
                END IF;
            END $$;
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE TABLE IF NOT EXISTS "ColumnMappingTransformRules" (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "ImportColumnMappingId" bigint NOT NULL,
                "TransformRuleId" bigint NOT NULL,
                "Order" integer NOT NULL,
                "ParametersJson" jsonb NULL
            );
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ColumnMappingTransformRules_ImportColumnMappingId_Order"
            ON "ColumnMappingTransformRules" ("ImportColumnMappingId", "Order");
            """,
            cancellationToken);

        await db.Database.ExecuteSqlRawAsync(
            """
            CREATE INDEX IF NOT EXISTS "IX_ColumnMappingTransformRules_TransformRuleId"
            ON "ColumnMappingTransformRules" ("TransformRuleId");
            """,
            cancellationToken);
    }

    private static async Task EnsureTransformRulesCatalogAsync(ImportDbContext db, CancellationToken cancellationToken)
    {
        var catalog = await db.TransformRules.ToListAsync(cancellationToken);

        UpsertTransformRule(catalog, db, "Trim", "Trim", "Remove espacos no inicio/fim.");
        UpsertTransformRule(catalog, db, "OnlyDigits", "Somente Digitos", "Mantem apenas digitos.");
        UpsertTransformRule(catalog, db, "BrazilianCurrency", "Moeda BR", "Converte texto monetario pt-BR para decimal.");
        UpsertTransformRule(catalog, db, "BrazilianDate", "Data BR", "Converte texto de data para DateTime.");
        UpsertTransformRule(catalog, db, "UpperCase", "Maiusculo", "Converte texto para maiusculo.");
        UpsertTransformRule(catalog, db, "LowerCase", "Minusculo", "Converte texto para minusculo.");

        await db.SaveChangesAsync(cancellationToken);
    }

    private static async Task EnsureSalesInvoiceTemplateV2Async(ImportDbContext db, CancellationToken cancellationToken)
    {
        var salesType = await db.ImportFileTypes
            .FirstOrDefaultAsync(x => x.Code == ImportFileTypeCodes.SalesInvoice, cancellationToken);
        if (salesType is null)
        {
            return;
        }

        var template = await db.ImportTemplates
            .Include(x => x.ColumnMappings)
                .ThenInclude(x => x.TransformRules)
            .FirstOrDefaultAsync(
                x => x.ImportFileTypeId == salesType.Id && x.Name == "Template NF Saida - Itens de Venda",
                cancellationToken);

        if (template is null)
        {
            template = new ImportTemplate
            {
                ImportFileTypeId = salesType.Id,
                Name = "Template NF Saida - Itens de Venda",
                Description = "Template para ITEM DE VENDA (NOTAS FISCAIS DE SAIDA).xlsx",
                IsActive = true,
                FileNamePattern = "ITEM DE VENDA(NOTAS FISCAIS DE SAIDA);ITEM DE VENDA",
                RequiredHeadersCsv = "documento,data,cliente,nome,produto,descricao,quantidade,vlr. unit.,total,tipo,cidade,grupo descricao,peso bruto(kg)",
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            db.ImportTemplates.Add(template);
            await db.SaveChangesAsync(cancellationToken);
        }
        else
        {
            template.Description = "Template para ITEM DE VENDA (NOTAS FISCAIS DE SAIDA).xlsx";
            template.IsActive = true;
            template.FileNamePattern = "ITEM DE VENDA(NOTAS FISCAIS DE SAIDA);ITEM DE VENDA";
            template.RequiredHeadersCsv = "documento,data,cliente,nome,produto,descricao,quantidade,vlr. unit.,total,tipo,cidade,grupo descricao,peso bruto(kg)";
            template.UpdatedAt = DateTime.UtcNow;
        }

        var rulesByCode = await db.TransformRules
            .Where(x => x.IsActive)
            .ToDictionaryAsync(x => x.Code, StringComparer.OrdinalIgnoreCase, cancellationToken);

        UpsertColumnMapping(
            template,
            "documento",
            "documentnumber",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "data",
            "transactiondate",
            true,
            null,
            [("Trim", 1, null), ("BrazilianDate", 2, """{"formats":["yyyyMMdd","dd/MM/yyyy","yyyy-MM-dd","MM/dd/yyyy"]}""")],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "cliente",
            "customercode",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "nome",
            "customername",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "produto",
            "productcode",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "descricao",
            "productdescription",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "quantidade",
            "quantity",
            true,
            null,
            [("Trim", 1, null), ("BrazilianCurrency", 2, """{"culture":"pt-BR"}""")],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "vlr. unit.",
            "unitprice",
            true,
            null,
            [("Trim", 1, null), ("BrazilianCurrency", 2, """{"culture":"pt-BR"}""")],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "total",
            "totalamount",
            true,
            null,
            [("Trim", 1, null), ("BrazilianCurrency", 2, """{"culture":"pt-BR"}""")],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "tipo",
            "transactiontype",
            false,
            string.Empty,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "cidade",
            "city",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "grupo descricao",
            "productgroup",
            true,
            null,
            [("Trim", 1, null)],
            rulesByCode);
        UpsertColumnMapping(
            template,
            "peso bruto(kg)",
            "grossweightkg",
            true,
            null,
            [("Trim", 1, null), ("BrazilianCurrency", 2, """{"culture":"pt-BR"}""")],
            rulesByCode);

        await db.SaveChangesAsync(cancellationToken);
    }

    private static void UpsertTransformRule(ICollection<TransformRule> catalog, ImportDbContext db, string code, string name, string description)
    {
        var existing = catalog.FirstOrDefault(x => x.Code == code);
        if (existing is not null)
        {
            existing.Name = name;
            existing.Description = description;
            existing.IsActive = true;
            return;
        }

        var created = new TransformRule
        {
            Code = code,
            Name = name,
            Description = description,
            IsActive = true
        };
        catalog.Add(created);
        db.TransformRules.Add(created);
    }

    private static void UpsertColumnMapping(
        ImportTemplate template,
        string sourceColumnName,
        string targetFieldName,
        bool isRequired,
        string? defaultValue,
        IReadOnlyList<(string RuleCode, int Order, string? ParametersJson)> ruleConfigs,
        IReadOnlyDictionary<string, TransformRule> rulesByCode)
    {
        var mapping = template.ColumnMappings.FirstOrDefault(x => x.TargetFieldName == targetFieldName);
        if (mapping is null)
        {
            mapping = new ImportColumnMapping
            {
                SourceColumnName = sourceColumnName,
                TargetFieldName = targetFieldName,
                IsRequired = isRequired,
                DefaultValue = defaultValue,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow
            };
            template.ColumnMappings.Add(mapping);
        }
        else
        {
            mapping.SourceColumnName = sourceColumnName;
            mapping.IsRequired = isRequired;
            mapping.DefaultValue = defaultValue;
            mapping.UpdatedAt = DateTime.UtcNow;
            mapping.TransformRules.Clear();
        }

        foreach (var (ruleCode, order, parametersJson) in ruleConfigs)
        {
            if (!rulesByCode.TryGetValue(ruleCode, out var transformRule))
            {
                continue;
            }

            mapping.TransformRules.Add(new ColumnMappingTransformRule
            {
                TransformRuleId = transformRule.Id,
                Order = order,
                ParametersJson = parametersJson
            });
        }
    }

    private static PreProcessorTemplate UpsertTemplate(
        ImportDbContext db,
        IList<PreProcessorTemplate> templates,
        string code,
        string name,
        FileType fileType,
        string fileNamePattern,
        string requiredHeadersCsv)
    {
        var existing = templates.FirstOrDefault(x => x.Code == code);
        if (existing is not null)
        {
            existing.Name = name;
            existing.IsActive = true;
            existing.FileType = fileType;
            existing.FileNamePattern = fileNamePattern;
            existing.RequiredHeadersCsv = requiredHeadersCsv;
            existing.UpdatedAt = DateTime.UtcNow;
            return existing;
        }

        var created = new PreProcessorTemplate
        {
            Code = code,
            Name = name,
            IsActive = true,
            FileType = fileType,
            FileNamePattern = fileNamePattern,
            RequiredHeadersCsv = requiredHeadersCsv,
            ColumnMappingsJson = string.Empty,
            ValidationRulesJson = string.Empty,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
            Rules = []
        };

        db.PreProcessorTemplates.Add(created);
        templates.Add(created);
        return created;
    }

    private static void UpsertRule(
        PreProcessorTemplate template,
        string name,
        string ruleType,
        bool isEnabled,
        string configJson,
        int sortOrder)
    {
        var existing = template.Rules.FirstOrDefault(x => x.Name == name);
        if (existing is not null)
        {
            existing.RuleType = ruleType;
            existing.IsEnabled = isEnabled;
            existing.ConfigJson = configJson;
            existing.SortOrder = sortOrder;
            return;
        }

        template.Rules.Add(new PreProcessorTemplateRule
        {
            Name = name,
            RuleType = ruleType,
            IsEnabled = isEnabled,
            ConfigJson = configJson,
            SortOrder = sortOrder
        });
    }
}
