-- =============================================
-- Core Tables: Jobs, FileJobs, ImportErrors
-- =============================================

CREATE TABLE IF NOT EXISTS "Jobs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Type" character varying(128) NOT NULL,
    "Status" integer NOT NULL,
    "ProgressPercent" integer NOT NULL,
    "CurrentStep" character varying(128) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone NULL,
    "FinishedAt" timestamp with time zone NULL,
    "UserId" character varying(128) NULL,
    "PayloadJson" jsonb NOT NULL,
    "ResultJson" jsonb NULL,
    "Error" character varying(4000) NOT NULL,
    "RetryCount" integer NOT NULL,
    "LockedBy" character varying(128) NOT NULL,
    "LockedAt" timestamp with time zone NULL
);
CREATE INDEX IF NOT EXISTS "IX_Jobs_Status_CreatedAt" ON "Jobs" ("Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Jobs_Type_Status_CreatedAt" ON "Jobs" ("Type", "Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Jobs_LockedAt" ON "Jobs" ("LockedAt");

CREATE TABLE IF NOT EXISTS "FileJobs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FilePath" character varying(1024) NOT NULL,
    "OriginalFileName" character varying(512) NOT NULL DEFAULT '',
    "NormalizedFilePath" character varying(1024) NOT NULL,
    "ImportFileTypeCode" character varying(64) NULL,
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "CurrentStep" character varying(128) NOT NULL,
    "ProgressPercent" integer NOT NULL,
    "ProcessedRows" integer NOT NULL,
    "TotalRows" integer NOT NULL,
    "LastHeartbeatAt" timestamp with time zone NOT NULL,
    "StartedAt" timestamp with time zone NULL,
    "FinishedAt" timestamp with time zone NULL,
    "LockedBy" character varying(128) NOT NULL DEFAULT '',
    "LockedAt" timestamp with time zone NULL
);
CREATE INDEX IF NOT EXISTS "IX_FileJobs_Status_CreatedAt" ON "FileJobs" ("Status", "CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_FileJobs_Status_LastHeartbeatAt" ON "FileJobs" ("Status", "LastHeartbeatAt");
CREATE INDEX IF NOT EXISTS "IX_FileJobs_LockedAt" ON "FileJobs" ("LockedAt");

CREATE TABLE IF NOT EXISTS "ImportErrors" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FileJobId" bigint NOT NULL,
    "RowNumber" integer NOT NULL,
    "Stage" character varying(64) NOT NULL DEFAULT '',
    "Column" character varying(128) NOT NULL,
    "Message" character varying(1024) NOT NULL,
    "RecordIdentifier" character varying(256) NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ImportErrors_FileJobId" ON "ImportErrors" ("FileJobId");
CREATE INDEX IF NOT EXISTS "IX_ImportErrors_FileJobId_Stage" ON "ImportErrors" ("FileJobId", "Stage");
