-- =============================================
-- Processing Monitoring Tables
-- =============================================

CREATE TABLE IF NOT EXISTS "ProcessingStepExecutions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FileJobId" bigint NOT NULL,
    "Step" character varying(64) NOT NULL,
    "StartedAt" timestamp with time zone NOT NULL,
    "FinishedAt" timestamp with time zone NULL,
    "Status" character varying(32) NOT NULL,
    "ProcessedRows" integer NOT NULL,
    "ErrorCount" integer NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ProcessingStepExecutions_FileJobId" ON "ProcessingStepExecutions" ("FileJobId");
CREATE INDEX IF NOT EXISTS "IX_ProcessingStepExecutions_Step_StartedAt" ON "ProcessingStepExecutions" ("Step", "StartedAt");

CREATE TABLE IF NOT EXISTS "ProcessingJobLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FileJobId" bigint NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "Stage" character varying(64) NOT NULL,
    "Level" character varying(32) NOT NULL,
    "Message" character varying(1024) NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ProcessingJobLogs_FileJobId_Timestamp" ON "ProcessingJobLogs" ("FileJobId", "Timestamp");

CREATE TABLE IF NOT EXISTS "ProcessingJobEventLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FileJobId" bigint NOT NULL,
    "EventType" character varying(128) NOT NULL,
    "Status" character varying(32) NOT NULL,
    "CorrelationId" uuid NOT NULL,
    "RetryCount" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ProcessedAt" timestamp with time zone NULL,
    "ErrorMessage" character varying(1024) NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ProcessingJobEventLogs_FileJobId_EventType_CorrelationId" ON "ProcessingJobEventLogs" ("FileJobId", "EventType", "CorrelationId");
CREATE INDEX IF NOT EXISTS "IX_ProcessingJobEventLogs_Status_CreatedAt" ON "ProcessingJobEventLogs" ("Status", "CreatedAt");

CREATE TABLE IF NOT EXISTS "WorkerHeartbeats" (
    "WorkerId" character varying(128) PRIMARY KEY,
    "LastSeenAt" timestamp with time zone NOT NULL,
    "ProcessedJobsToday" integer NOT NULL,
    "IdleSinceAt" timestamp with time zone NULL,
    "CurrentJobId" bigint NULL,
    "CurrentTask" character varying(128) NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_WorkerHeartbeats_LastSeenAt" ON "WorkerHeartbeats" ("LastSeenAt");

-- Hangfire schema (managed by Hangfire, created automatically)
-- Schema name: hangfire
