-- =============================================
-- Business Domain Tables
-- =============================================

CREATE TABLE IF NOT EXISTS "Customers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CustomerCode" character varying(64) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "SourceFileJobId" bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Customers_CustomerCode" ON "Customers" ("CustomerCode");
CREATE INDEX IF NOT EXISTS "IX_Customers_Email" ON "Customers" ("Email");
CREATE INDEX IF NOT EXISTS "IX_Customers_SourceFileJobId" ON "Customers" ("SourceFileJobId");

CREATE TABLE IF NOT EXISTS "Products" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Sku" character varying(64) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "SourceFileJobId" bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Products_Sku" ON "Products" ("Sku");
CREATE INDEX IF NOT EXISTS "IX_Products_Name" ON "Products" ("Name");
CREATE INDEX IF NOT EXISTS "IX_Products_SourceFileJobId" ON "Products" ("SourceFileJobId");

CREATE TABLE IF NOT EXISTS "Orders" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "OrderNumber" character varying(64) NOT NULL,
    "CustomerEmail" character varying(256) NOT NULL,
    "ProductSku" character varying(64) NOT NULL,
    "Quantity" integer NOT NULL,
    "OrderedAt" timestamp with time zone NOT NULL,
    "SourceFileJobId" bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_Orders_BusinessKey" ON "Orders" ("OrderNumber", "CustomerEmail", "ProductSku", "OrderedAt");
CREATE INDEX IF NOT EXISTS "IX_Orders_SourceFileJobId" ON "Orders" ("SourceFileJobId");

CREATE TABLE IF NOT EXISTS "CommercialTransactions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "DocumentNumber" character varying(64) NOT NULL,
    "TransactionDate" timestamp with time zone NOT NULL,
    "CustomerCode" character varying(64) NOT NULL,
    "CustomerName" character varying(256) NOT NULL,
    "ProductCode" character varying(64) NOT NULL,
    "ProductDescription" character varying(512) NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "UnitPrice" numeric(18,2) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "TransactionType" character varying(128) NOT NULL,
    "City" character varying(256) NOT NULL,
    "ProductGroup" character varying(128) NOT NULL,
    "GrossWeightKg" numeric(18,3) NOT NULL,
    "SourceFileJobId" bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_DocumentNumber" ON "CommercialTransactions" ("DocumentNumber");
CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_SourceFileJobId" ON "CommercialTransactions" ("SourceFileJobId");
CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_TransactionDate" ON "CommercialTransactions" ("TransactionDate");
CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_CustomerName" ON "CommercialTransactions" ("CustomerName");
CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_ProductCode" ON "CommercialTransactions" ("ProductCode");
CREATE INDEX IF NOT EXISTS "IX_CommercialTransactions_City" ON "CommercialTransactions" ("City");
CREATE UNIQUE INDEX IF NOT EXISTS "UQ_CommercialTransactions_BusinessKey" ON "CommercialTransactions"
    ("DocumentNumber", "TransactionDate", "CustomerCode", "ProductCode", "TransactionType", "City", "ProductGroup", "Quantity", "UnitPrice", "GrossWeightKg");
