-- =============================================
-- Summary / Analytics Tables
-- =============================================

-- Sales Summaries
CREATE TABLE IF NOT EXISTS "SalesSummariesDaily" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceFileJobId" bigint NOT NULL,
    "ReferenceDate" timestamp with time zone NOT NULL,
    "City" character varying(256) NOT NULL,
    "ProductGroup" character varying(128) NOT NULL,
    "TransactionType" character varying(128) NOT NULL,
    "TransactionCount" integer NOT NULL,
    "TotalQuantity" numeric(18,3) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "TotalGrossWeightKg" numeric(18,3) NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_SourceFileJobId" ON "SalesSummariesDaily" ("SourceFileJobId");
CREATE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_ReferenceDate" ON "SalesSummariesDaily" ("ReferenceDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesSummariesDaily_SourceFileJobId_Date_City_Group_Type"
    ON "SalesSummariesDaily" ("SourceFileJobId", "ReferenceDate", "City", "ProductGroup", "TransactionType");

CREATE TABLE IF NOT EXISTS "SalesSummariesWeekly" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceFileJobId" bigint NOT NULL,
    "WeekStartDate" timestamp with time zone NOT NULL,
    "City" character varying(256) NOT NULL,
    "ProductGroup" character varying(128) NOT NULL,
    "TransactionType" character varying(128) NOT NULL,
    "TransactionCount" integer NOT NULL,
    "TotalQuantity" numeric(18,3) NOT NULL,
    "TotalAmount" numeric(18,2) NOT NULL,
    "TotalGrossWeightKg" numeric(18,3) NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_SourceFileJobId" ON "SalesSummariesWeekly" ("SourceFileJobId");
CREATE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_WeekStartDate" ON "SalesSummariesWeekly" ("WeekStartDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesSummariesWeekly_SourceFileJobId_Week_City_Group_Type"
    ON "SalesSummariesWeekly" ("SourceFileJobId", "WeekStartDate", "City", "ProductGroup", "TransactionType");

-- Customer Summaries
CREATE TABLE IF NOT EXISTS "CustomerSummariesDaily" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceFileJobId" bigint NOT NULL,
    "ReferenceDate" timestamp with time zone NOT NULL,
    "CustomerCode" character varying(64) NOT NULL,
    "CustomerName" character varying(256) NOT NULL,
    "City" character varying(256) NOT NULL,
    "ProductGroup" character varying(128) NOT NULL,
    "TransactionType" character varying(128) NOT NULL,
    "Orders" integer NOT NULL,
    "Revenue" numeric(18,2) NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Weight" numeric(18,3) NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_SourceFileJobId" ON "CustomerSummariesDaily" ("SourceFileJobId");
CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_ReferenceDate" ON "CustomerSummariesDaily" ("ReferenceDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerSummariesDaily_UQ_BySourceAndDimensions"
    ON "CustomerSummariesDaily" ("SourceFileJobId", "ReferenceDate", "CustomerCode", "City", "ProductGroup", "TransactionType");

CREATE TABLE IF NOT EXISTS "CustomerSummariesWeekly" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceFileJobId" bigint NOT NULL,
    "WeekStartDate" timestamp with time zone NOT NULL,
    "CustomerCode" character varying(64) NOT NULL,
    "CustomerName" character varying(256) NOT NULL,
    "City" character varying(256) NOT NULL,
    "ProductGroup" character varying(128) NOT NULL,
    "TransactionType" character varying(128) NOT NULL,
    "Orders" integer NOT NULL,
    "Revenue" numeric(18,2) NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Weight" numeric(18,3) NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_SourceFileJobId" ON "CustomerSummariesWeekly" ("SourceFileJobId");
CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_WeekStartDate" ON "CustomerSummariesWeekly" ("WeekStartDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerSummariesWeekly_UQ_BySourceAndDimensions"
    ON "CustomerSummariesWeekly" ("SourceFileJobId", "WeekStartDate", "CustomerCode", "City", "ProductGroup", "TransactionType");

CREATE TABLE IF NOT EXISTS "CustomerSummariesMonthly" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SourceFileJobId" bigint NOT NULL,
    "MonthStartDate" timestamp with time zone NOT NULL,
    "CustomerCode" character varying(64) NOT NULL,
    "CustomerName" character varying(256) NOT NULL,
    "City" character varying(256) NOT NULL,
    "ProductGroup" character varying(128) NOT NULL,
    "TransactionType" character varying(128) NOT NULL,
    "Orders" integer NOT NULL,
    "Revenue" numeric(18,2) NOT NULL,
    "Quantity" numeric(18,3) NOT NULL,
    "Weight" numeric(18,3) NOT NULL,
    "ProcessedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_SourceFileJobId" ON "CustomerSummariesMonthly" ("SourceFileJobId");
CREATE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_MonthStartDate" ON "CustomerSummariesMonthly" ("MonthStartDate");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_CustomerSummariesMonthly_UQ_BySourceAndDimensions"
    ON "CustomerSummariesMonthly" ("SourceFileJobId", "MonthStartDate", "CustomerCode", "City", "ProductGroup", "TransactionType");
