-- =============================================
-- Analytics / BI Tables & Materialized Views
-- =============================================

-- Client Indicators (calculated scores, trends, classification)
CREATE TABLE IF NOT EXISTS "cliente_indicadores" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClienteId" character varying(64) NOT NULL,
    "Faturamento3M" numeric(18,2) NOT NULL DEFAULT 0,
    "Faturamento6M" numeric(18,2) NOT NULL DEFAULT 0,
    "Faturamento12M" numeric(18,2) NOT NULL DEFAULT 0,
    "Crescimento3M" numeric(18,2) NULL,
    "Crescimento6M" numeric(18,2) NULL,
    "Crescimento12M" numeric(18,2) NULL,
    "MediaMovel3M" numeric(18,2) NOT NULL DEFAULT 0,
    "MediaMovel6M" numeric(18,2) NOT NULL DEFAULT 0,
    "MediaMovel12M" numeric(18,2) NOT NULL DEFAULT 0,
    "FrequenciaCompra" numeric(18,2) NOT NULL DEFAULT 0,
    "TicketMedioGeral" numeric(18,2) NOT NULL DEFAULT 0,
    "ScoreCrescimento" integer NOT NULL DEFAULT 0,
    "ScoreFrequencia" integer NOT NULL DEFAULT 0,
    "ScoreTicket" integer NOT NULL DEFAULT 0,
    "ScoreRecencia" integer NOT NULL DEFAULT 0,
    "ScorePotencial" integer NOT NULL DEFAULT 0,
    "Tendencia" character varying(32) NOT NULL DEFAULT 'Estavel',
    "Classificacao" character varying(4) NOT NULL DEFAULT 'C',
    "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_cliente_indicadores_cliente_id" ON "cliente_indicadores" ("ClienteId");
CREATE INDEX IF NOT EXISTS "IX_cliente_indicadores_score" ON "cliente_indicadores" ("ScorePotencial");
CREATE INDEX IF NOT EXISTS "IX_cliente_indicadores_classificacao" ON "cliente_indicadores" ("Classificacao");
CREATE INDEX IF NOT EXISTS "IX_cliente_indicadores_tendencia" ON "cliente_indicadores" ("Tendencia");

-- Client Forecast (Holt-Winters predictions)
CREATE TABLE IF NOT EXISTS "cliente_forecast" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ClienteId" character varying(64) NOT NULL,
    "Previsao30Dias" numeric(18,2) NOT NULL DEFAULT 0,
    "Previsao60Dias" numeric(18,2) NOT NULL DEFAULT 0,
    "Previsao90Dias" numeric(18,2) NOT NULL DEFAULT 0,
    "TendenciaPrevista" character varying(32) NOT NULL DEFAULT 'Estavel',
    "ErroMedioHistorico" numeric(18,2) NULL,
    "ConfiancaModelo" numeric(5,2) NULL,
    "UltimaObservacao" timestamp with time zone NOT NULL DEFAULT NOW(),
    "AtualizadoEm" timestamp with time zone NOT NULL DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_cliente_forecast_cliente_id" ON "cliente_forecast" ("ClienteId");

-- Materialized View: Monthly customer metrics
CREATE MATERIALIZED VIEW IF NOT EXISTS mv_cliente_metricas_mensais AS
SELECT
    "CustomerCode" AS cliente_id,
    TO_CHAR("TransactionDate", 'YYYY-MM') AS ano_mes,
    COALESCE(SUM("TotalAmount"), 0) AS faturamento_total,
    COUNT(DISTINCT "DocumentNumber")::int AS quantidade_notas,
    CASE
        WHEN COUNT(DISTINCT "DocumentNumber") > 0
        THEN COALESCE(SUM("TotalAmount"), 0) / COUNT(DISTINCT "DocumentNumber")
        ELSE 0
    END AS ticket_medio,
    MIN("TransactionDate") AS primeiro_faturamento_mes,
    MAX("TransactionDate") AS ultimo_faturamento_mes
FROM "CommercialTransactions"
GROUP BY "CustomerCode", TO_CHAR("TransactionDate", 'YYYY-MM')
ORDER BY "CustomerCode", ano_mes;

CREATE UNIQUE INDEX IF NOT EXISTS "IX_mv_cliente_metricas_mensais_pk"
    ON mv_cliente_metricas_mensais (cliente_id, ano_mes);
CREATE INDEX IF NOT EXISTS "IX_mv_cliente_metricas_mensais_cliente_id"
    ON mv_cliente_metricas_mensais (cliente_id);
CREATE INDEX IF NOT EXISTS "IX_mv_cliente_metricas_mensais_ano_mes"
    ON mv_cliente_metricas_mensais (ano_mes);
