-- =============================================
-- Auth / Users & Import Configuration Tables
-- =============================================

CREATE TABLE IF NOT EXISTS "AppUsers" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" character varying(256) NOT NULL,
    "Email" character varying(256) NOT NULL,
    "Role" character varying(64) NOT NULL DEFAULT 'gestor',
    "PasswordHash" character varying(1024) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppUsers_Email" ON "AppUsers" ("Email");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_AppUsers_Name" ON "AppUsers" ("Name");

CREATE TABLE IF NOT EXISTS "ImportFileTypes" (
    "Id" uuid PRIMARY KEY,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(256) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "AllowedExtensions" character varying(256) NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_ImportFileTypes_Code" ON "ImportFileTypes" ("Code");
CREATE INDEX IF NOT EXISTS "IX_ImportFileTypes_IsActive" ON "ImportFileTypes" ("IsActive");

INSERT INTO "ImportFileTypes" ("Id", "Code", "Name", "Description", "AllowedExtensions", "IsActive", "CreatedAt", "UpdatedAt")
VALUES
    ('11111111-1111-1111-1111-111111111111', 'SALES_INVOICE', 'Nota Fiscal de Venda', 'Importacao de notas fiscais de venda', '.csv,.xlsx', true, NOW(), NOW()),
    ('22222222-2222-2222-2222-222222222222', 'CUSTOMER_LIST', 'Clientes', 'Importacao da tabela de clientes', '.csv,.xlsx', true, NOW(), NOW()),
    ('33333333-3333-3333-3333-333333333333', 'PRODUCT_LIST', 'Produtos', 'Importacao da tabela de produtos', '.csv,.xlsx', true, NOW(), NOW()),
    ('44444444-4444-4444-4444-444444444444', 'FINANCIAL_ENTRY', 'Lancamento Financeiro', 'Importacao de pedidos/lancamentos', '.csv,.xlsx', true, NOW(), NOW()),
    ('55555555-5555-5555-5555-555555555555', 'ROUTE_PLANNING', 'Rotas por Cidade', 'Importacao de planejamento de rotas por cidade e dia', '.xlsx', true, NOW(), NOW())
ON CONFLICT ("Code") DO NOTHING;

CREATE TABLE IF NOT EXISTS "ImportTemplatesV2" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ImportFileTypeId" uuid NULL,
    "Name" character varying(256) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "IsActive" boolean NOT NULL,
    "FileNamePattern" character varying(256) NOT NULL,
    "RequiredHeadersCsv" character varying(2048) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ImportTemplatesV2_IsActive" ON "ImportTemplatesV2" ("IsActive");
CREATE INDEX IF NOT EXISTS "IX_ImportTemplatesV2_ImportFileTypeId" ON "ImportTemplatesV2" ("ImportFileTypeId");

CREATE TABLE IF NOT EXISTS "ImportColumnMappings" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ImportTemplateId" bigint NOT NULL,
    "SourceColumnName" character varying(256) NOT NULL,
    "TargetFieldName" character varying(256) NOT NULL,
    "IsRequired" boolean NOT NULL,
    "DefaultValue" character varying(4000) NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_ImportColumnMappings_ImportTemplateId_TargetFieldName"
    ON "ImportColumnMappings" ("ImportTemplateId", "TargetFieldName");

CREATE TABLE IF NOT EXISTS "TransformRules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Code" character varying(64) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT true
);
CREATE UNIQUE INDEX IF NOT EXISTS "IX_TransformRules_Code" ON "TransformRules" ("Code");

CREATE TABLE IF NOT EXISTS "ColumnMappingTransformRules" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ImportColumnMappingId" bigint NOT NULL,
    "TransformRuleId" bigint NOT NULL,
    "Order" integer NOT NULL,
    "IsEnabled" boolean NOT NULL DEFAULT true,
    "ParametersJson" jsonb NULL
);
CREATE INDEX IF NOT EXISTS "IX_ColumnMappingTransformRules_ImportColumnMappingId_Order"
    ON "ColumnMappingTransformRules" ("ImportColumnMappingId", "Order");
