<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InovaSkill.Importer.Application\InovaSkill.Importer.Application.csproj" />
    <ProjectReference Include="..\InovaSkill.Importer.Domain\InovaSkill.Importer.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.104.*" />
    <PackageReference Include="Cronos" Version="0.11.*" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.*" />
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.*" />
    <PackageReference Include="Hangfire.PostgreSql" Version="1.20.*" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.*" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.*" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Data\municipios.csv" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
