name: inovaskill-grespan

services:
  postgres:
    image: postgres:16-alpine
    container_name: inovaskill-postgres
    environment:
      POSTGRES_DB: inovaskill_importer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inovaskill_importer"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1.0

volumes:
  postgres_data:
