/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as ReunioesRouteImport } from './routes/reunioes'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProcessamentosRouteImport } from './routes/processamentos'
import { Route as PendenciasRouteImport } from './routes/pendencias'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ClientesImpactoRouteImport } from './routes/clientes-impacto'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AdministrativoRouteImport } from './routes/administrativo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReunioesIndexRouteImport } from './routes/reunioes.index'
import { Route as LogisticaIndexRouteImport } from './routes/logistica.index'
import { Route as ImportacoesIndexRouteImport } from './routes/importacoes.index'
import { Route as ReunioesIdRouteImport } from './routes/reunioes.$id'
import { Route as LogisticaMapaRouteImport } from './routes/logistica.mapa'
import { Route as ImportacoesFilesRouteImport } from './routes/importacoes.files'
import { Route as ClientesAnaliseComercialRouteImport } from './routes/clientes.analise-comercial'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesRoute = ReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessamentosRoute = ProcessamentosRouteImport.update({
  id: '/processamentos',
  path: '/processamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const PendenciasRoute = PendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesImpactoRoute = ClientesImpactoRouteImport.update({
  id: '/clientes-impacto',
  path: '/clientes-impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrativoRoute = AdministrativoRouteImport.update({
  id: '/administrativo',
  path: '/administrativo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReunioesIndexRoute = ReunioesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReunioesRoute,
} as any)
const LogisticaIndexRoute = LogisticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogisticaRoute,
} as any)
const ImportacoesIndexRoute = ImportacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportacoesRoute,
} as any)
const ReunioesIdRoute = ReunioesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReunioesRoute,
} as any)
const LogisticaMapaRoute = LogisticaMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => LogisticaRoute,
} as any)
const ImportacoesFilesRoute = ImportacoesFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ImportacoesRoute,
} as any)
const ClientesAnaliseComercialRoute =
  ClientesAnaliseComercialRouteImport.update({
    id: '/analise-comercial',
    path: '/analise-comercial',
    getParentRoute: () => ClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrativo': typeof AdministrativoRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes-impacto': typeof ClientesImpactoRoute
  '/financas': typeof FinancasRoute
  '/importacoes': typeof ImportacoesRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRouteWithChildren
  '/notificacoes': typeof NotificacoesRoute
  '/pendencias': typeof PendenciasRoute
  '/processamentos': typeof ProcessamentosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/simulacao': typeof SimulacaoRoute
  '/vendas': typeof VendasRoute
  '/clientes/analise-comercial': typeof ClientesAnaliseComercialRoute
  '/importacoes/files': typeof ImportacoesFilesRoute
  '/logistica/mapa': typeof LogisticaMapaRoute
  '/reunioes/$id': typeof ReunioesIdRoute
  '/importacoes/': typeof ImportacoesIndexRoute
  '/logistica/': typeof LogisticaIndexRoute
  '/reunioes/': typeof ReunioesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrativo': typeof AdministrativoRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes-impacto': typeof ClientesImpactoRoute
  '/financas': typeof FinancasRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRoute
  '/pendencias': typeof PendenciasRoute
  '/processamentos': typeof ProcessamentosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
  '/vendas': typeof VendasRoute
  '/clientes/analise-comercial': typeof ClientesAnaliseComercialRoute
  '/importacoes/files': typeof ImportacoesFilesRoute
  '/logistica/mapa': typeof LogisticaMapaRoute
  '/reunioes/$id': typeof ReunioesIdRoute
  '/importacoes': typeof ImportacoesIndexRoute
  '/logistica': typeof LogisticaIndexRoute
  '/reunioes': typeof ReunioesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrativo': typeof AdministrativoRoute
  '/alertas': typeof AlertasRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes-impacto': typeof ClientesImpactoRoute
  '/financas': typeof FinancasRoute
  '/importacoes': typeof ImportacoesRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRouteWithChildren
  '/notificacoes': typeof NotificacoesRoute
  '/pendencias': typeof PendenciasRoute
  '/processamentos': typeof ProcessamentosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reunioes': typeof ReunioesRouteWithChildren
  '/simulacao': typeof SimulacaoRoute
  '/vendas': typeof VendasRoute
  '/clientes/analise-comercial': typeof ClientesAnaliseComercialRoute
  '/importacoes/files': typeof ImportacoesFilesRoute
  '/logistica/mapa': typeof LogisticaMapaRoute
  '/reunioes/$id': typeof ReunioesIdRoute
  '/importacoes/': typeof ImportacoesIndexRoute
  '/logistica/': typeof LogisticaIndexRoute
  '/reunioes/': typeof ReunioesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrativo'
    | '/alertas'
    | '/clientes'
    | '/clientes-impacto'
    | '/financas'
    | '/importacoes'
    | '/landing'
    | '/login'
    | '/logistica'
    | '/notificacoes'
    | '/pendencias'
    | '/processamentos'
    | '/produtos'
    | '/relatorios'
    | '/reunioes'
    | '/simulacao'
    | '/vendas'
    | '/clientes/analise-comercial'
    | '/importacoes/files'
    | '/logistica/mapa'
    | '/reunioes/$id'
    | '/importacoes/'
    | '/logistica/'
    | '/reunioes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrativo'
    | '/alertas'
    | '/clientes'
    | '/clientes-impacto'
    | '/financas'
    | '/landing'
    | '/login'
    | '/notificacoes'
    | '/pendencias'
    | '/processamentos'
    | '/produtos'
    | '/relatorios'
    | '/simulacao'
    | '/vendas'
    | '/clientes/analise-comercial'
    | '/importacoes/files'
    | '/logistica/mapa'
    | '/reunioes/$id'
    | '/importacoes'
    | '/logistica'
    | '/reunioes'
  id:
    | '__root__'
    | '/'
    | '/administrativo'
    | '/alertas'
    | '/clientes'
    | '/clientes-impacto'
    | '/financas'
    | '/importacoes'
    | '/landing'
    | '/login'
    | '/logistica'
    | '/notificacoes'
    | '/pendencias'
    | '/processamentos'
    | '/produtos'
    | '/relatorios'
    | '/reunioes'
    | '/simulacao'
    | '/vendas'
    | '/clientes/analise-comercial'
    | '/importacoes/files'
    | '/logistica/mapa'
    | '/reunioes/$id'
    | '/importacoes/'
    | '/logistica/'
    | '/reunioes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrativoRoute: typeof AdministrativoRoute
  AlertasRoute: typeof AlertasRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ClientesImpactoRoute: typeof ClientesImpactoRoute
  FinancasRoute: typeof FinancasRoute
  ImportacoesRoute: typeof ImportacoesRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  LogisticaRoute: typeof LogisticaRouteWithChildren
  NotificacoesRoute: typeof NotificacoesRoute
  PendenciasRoute: typeof PendenciasRoute
  ProcessamentosRoute: typeof ProcessamentosRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReunioesRoute: typeof ReunioesRouteWithChildren
  SimulacaoRoute: typeof SimulacaoRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes': {
      id: '/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof ReunioesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processamentos': {
      id: '/processamentos'
      path: '/processamentos'
      fullPath: '/processamentos'
      preLoaderRoute: typeof ProcessamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pendencias': {
      id: '/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof PendenciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes-impacto': {
      id: '/clientes-impacto'
      path: '/clientes-impacto'
      fullPath: '/clientes-impacto'
      preLoaderRoute: typeof ClientesImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrativo': {
      id: '/administrativo'
      path: '/administrativo'
      fullPath: '/administrativo'
      preLoaderRoute: typeof AdministrativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reunioes/': {
      id: '/reunioes/'
      path: '/'
      fullPath: '/reunioes/'
      preLoaderRoute: typeof ReunioesIndexRouteImport
      parentRoute: typeof ReunioesRoute
    }
    '/logistica/': {
      id: '/logistica/'
      path: '/'
      fullPath: '/logistica/'
      preLoaderRoute: typeof LogisticaIndexRouteImport
      parentRoute: typeof LogisticaRoute
    }
    '/importacoes/': {
      id: '/importacoes/'
      path: '/'
      fullPath: '/importacoes/'
      preLoaderRoute: typeof ImportacoesIndexRouteImport
      parentRoute: typeof ImportacoesRoute
    }
    '/reunioes/$id': {
      id: '/reunioes/$id'
      path: '/$id'
      fullPath: '/reunioes/$id'
      preLoaderRoute: typeof ReunioesIdRouteImport
      parentRoute: typeof ReunioesRoute
    }
    '/logistica/mapa': {
      id: '/logistica/mapa'
      path: '/mapa'
      fullPath: '/logistica/mapa'
      preLoaderRoute: typeof LogisticaMapaRouteImport
      parentRoute: typeof LogisticaRoute
    }
    '/importacoes/files': {
      id: '/importacoes/files'
      path: '/files'
      fullPath: '/importacoes/files'
      preLoaderRoute: typeof ImportacoesFilesRouteImport
      parentRoute: typeof ImportacoesRoute
    }
    '/clientes/analise-comercial': {
      id: '/clientes/analise-comercial'
      path: '/analise-comercial'
      fullPath: '/clientes/analise-comercial'
      preLoaderRoute: typeof ClientesAnaliseComercialRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesAnaliseComercialRoute: typeof ClientesAnaliseComercialRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesAnaliseComercialRoute: ClientesAnaliseComercialRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface ImportacoesRouteChildren {
  ImportacoesFilesRoute: typeof ImportacoesFilesRoute
  ImportacoesIndexRoute: typeof ImportacoesIndexRoute
}

const ImportacoesRouteChildren: ImportacoesRouteChildren = {
  ImportacoesFilesRoute: ImportacoesFilesRoute,
  ImportacoesIndexRoute: ImportacoesIndexRoute,
}

const ImportacoesRouteWithChildren = ImportacoesRoute._addFileChildren(
  ImportacoesRouteChildren,
)

interface LogisticaRouteChildren {
  LogisticaMapaRoute: typeof LogisticaMapaRoute
  LogisticaIndexRoute: typeof LogisticaIndexRoute
}

const LogisticaRouteChildren: LogisticaRouteChildren = {
  LogisticaMapaRoute: LogisticaMapaRoute,
  LogisticaIndexRoute: LogisticaIndexRoute,
}

const LogisticaRouteWithChildren = LogisticaRoute._addFileChildren(
  LogisticaRouteChildren,
)

interface ReunioesRouteChildren {
  ReunioesIdRoute: typeof ReunioesIdRoute
  ReunioesIndexRoute: typeof ReunioesIndexRoute
}

const ReunioesRouteChildren: ReunioesRouteChildren = {
  ReunioesIdRoute: ReunioesIdRoute,
  ReunioesIndexRoute: ReunioesIndexRoute,
}

const ReunioesRouteWithChildren = ReunioesRoute._addFileChildren(
  ReunioesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrativoRoute: AdministrativoRoute,
  AlertasRoute: AlertasRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ClientesImpactoRoute: ClientesImpactoRoute,
  FinancasRoute: FinancasRoute,
  ImportacoesRoute: ImportacoesRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  LogisticaRoute: LogisticaRouteWithChildren,
  NotificacoesRoute: NotificacoesRoute,
  PendenciasRoute: PendenciasRoute,
  ProcessamentosRoute: ProcessamentosRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReunioesRoute: ReunioesRouteWithChildren,
  SimulacaoRoute: SimulacaoRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
