/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulacaoRouteImport } from './routes/simulacao'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ProcessamentosRouteImport } from './routes/processamentos'
import { Route as LogisticaRouteImport } from './routes/logistica'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportacoesRouteImport } from './routes/importacoes'
import { Route as FinancasRouteImport } from './routes/financas'
import { Route as ClientesImpactoRouteImport } from './routes/clientes-impacto'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LogisticaIndexRouteImport } from './routes/logistica.index'
import { Route as ImportacoesIndexRouteImport } from './routes/importacoes.index'
import { Route as LogisticaMapaRouteImport } from './routes/logistica.mapa'
import { Route as ImportacoesFilesRouteImport } from './routes/importacoes.files'
import { Route as ClientesAnaliseComercialRouteImport } from './routes/clientes.analise-comercial'

const SimulacaoRoute = SimulacaoRouteImport.update({
  id: '/simulacao',
  path: '/simulacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessamentosRoute = ProcessamentosRouteImport.update({
  id: '/processamentos',
  path: '/processamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaRoute = LogisticaRouteImport.update({
  id: '/logistica',
  path: '/logistica',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportacoesRoute = ImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancasRoute = FinancasRouteImport.update({
  id: '/financas',
  path: '/financas',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesImpactoRoute = ClientesImpactoRouteImport.update({
  id: '/clientes-impacto',
  path: '/clientes-impacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticaIndexRoute = LogisticaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LogisticaRoute,
} as any)
const ImportacoesIndexRoute = ImportacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ImportacoesRoute,
} as any)
const LogisticaMapaRoute = LogisticaMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => LogisticaRoute,
} as any)
const ImportacoesFilesRoute = ImportacoesFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => ImportacoesRoute,
} as any)
const ClientesAnaliseComercialRoute =
  ClientesAnaliseComercialRouteImport.update({
    id: '/analise-comercial',
    path: '/analise-comercial',
    getParentRoute: () => ClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes-impacto': typeof ClientesImpactoRoute
  '/financas': typeof FinancasRoute
  '/importacoes': typeof ImportacoesRouteWithChildren
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRouteWithChildren
  '/processamentos': typeof ProcessamentosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
  '/clientes/analise-comercial': typeof ClientesAnaliseComercialRoute
  '/importacoes/files': typeof ImportacoesFilesRoute
  '/logistica/mapa': typeof LogisticaMapaRoute
  '/importacoes/': typeof ImportacoesIndexRoute
  '/logistica/': typeof LogisticaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes-impacto': typeof ClientesImpactoRoute
  '/financas': typeof FinancasRoute
  '/login': typeof LoginRoute
  '/processamentos': typeof ProcessamentosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
  '/clientes/analise-comercial': typeof ClientesAnaliseComercialRoute
  '/importacoes/files': typeof ImportacoesFilesRoute
  '/logistica/mapa': typeof LogisticaMapaRoute
  '/importacoes': typeof ImportacoesIndexRoute
  '/logistica': typeof LogisticaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRouteWithChildren
  '/clientes-impacto': typeof ClientesImpactoRoute
  '/financas': typeof FinancasRoute
  '/importacoes': typeof ImportacoesRouteWithChildren
  '/login': typeof LoginRoute
  '/logistica': typeof LogisticaRouteWithChildren
  '/processamentos': typeof ProcessamentosRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/simulacao': typeof SimulacaoRoute
  '/clientes/analise-comercial': typeof ClientesAnaliseComercialRoute
  '/importacoes/files': typeof ImportacoesFilesRoute
  '/logistica/mapa': typeof LogisticaMapaRoute
  '/importacoes/': typeof ImportacoesIndexRoute
  '/logistica/': typeof LogisticaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/clientes-impacto'
    | '/financas'
    | '/importacoes'
    | '/login'
    | '/logistica'
    | '/processamentos'
    | '/produtos'
    | '/relatorios'
    | '/simulacao'
    | '/clientes/analise-comercial'
    | '/importacoes/files'
    | '/logistica/mapa'
    | '/importacoes/'
    | '/logistica/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/clientes-impacto'
    | '/financas'
    | '/login'
    | '/processamentos'
    | '/produtos'
    | '/relatorios'
    | '/simulacao'
    | '/clientes/analise-comercial'
    | '/importacoes/files'
    | '/logistica/mapa'
    | '/importacoes'
    | '/logistica'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/clientes-impacto'
    | '/financas'
    | '/importacoes'
    | '/login'
    | '/logistica'
    | '/processamentos'
    | '/produtos'
    | '/relatorios'
    | '/simulacao'
    | '/clientes/analise-comercial'
    | '/importacoes/files'
    | '/logistica/mapa'
    | '/importacoes/'
    | '/logistica/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRouteWithChildren
  ClientesImpactoRoute: typeof ClientesImpactoRoute
  FinancasRoute: typeof FinancasRoute
  ImportacoesRoute: typeof ImportacoesRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogisticaRoute: typeof LogisticaRouteWithChildren
  ProcessamentosRoute: typeof ProcessamentosRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  SimulacaoRoute: typeof SimulacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulacao': {
      id: '/simulacao'
      path: '/simulacao'
      fullPath: '/simulacao'
      preLoaderRoute: typeof SimulacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processamentos': {
      id: '/processamentos'
      path: '/processamentos'
      fullPath: '/processamentos'
      preLoaderRoute: typeof ProcessamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica': {
      id: '/logistica'
      path: '/logistica'
      fullPath: '/logistica'
      preLoaderRoute: typeof LogisticaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/importacoes': {
      id: '/importacoes'
      path: '/importacoes'
      fullPath: '/importacoes'
      preLoaderRoute: typeof ImportacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financas': {
      id: '/financas'
      path: '/financas'
      fullPath: '/financas'
      preLoaderRoute: typeof FinancasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes-impacto': {
      id: '/clientes-impacto'
      path: '/clientes-impacto'
      fullPath: '/clientes-impacto'
      preLoaderRoute: typeof ClientesImpactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistica/': {
      id: '/logistica/'
      path: '/'
      fullPath: '/logistica/'
      preLoaderRoute: typeof LogisticaIndexRouteImport
      parentRoute: typeof LogisticaRoute
    }
    '/importacoes/': {
      id: '/importacoes/'
      path: '/'
      fullPath: '/importacoes/'
      preLoaderRoute: typeof ImportacoesIndexRouteImport
      parentRoute: typeof ImportacoesRoute
    }
    '/logistica/mapa': {
      id: '/logistica/mapa'
      path: '/mapa'
      fullPath: '/logistica/mapa'
      preLoaderRoute: typeof LogisticaMapaRouteImport
      parentRoute: typeof LogisticaRoute
    }
    '/importacoes/files': {
      id: '/importacoes/files'
      path: '/files'
      fullPath: '/importacoes/files'
      preLoaderRoute: typeof ImportacoesFilesRouteImport
      parentRoute: typeof ImportacoesRoute
    }
    '/clientes/analise-comercial': {
      id: '/clientes/analise-comercial'
      path: '/analise-comercial'
      fullPath: '/clientes/analise-comercial'
      preLoaderRoute: typeof ClientesAnaliseComercialRouteImport
      parentRoute: typeof ClientesRoute
    }
  }
}

interface ClientesRouteChildren {
  ClientesAnaliseComercialRoute: typeof ClientesAnaliseComercialRoute
}

const ClientesRouteChildren: ClientesRouteChildren = {
  ClientesAnaliseComercialRoute: ClientesAnaliseComercialRoute,
}

const ClientesRouteWithChildren = ClientesRoute._addFileChildren(
  ClientesRouteChildren,
)

interface ImportacoesRouteChildren {
  ImportacoesFilesRoute: typeof ImportacoesFilesRoute
  ImportacoesIndexRoute: typeof ImportacoesIndexRoute
}

const ImportacoesRouteChildren: ImportacoesRouteChildren = {
  ImportacoesFilesRoute: ImportacoesFilesRoute,
  ImportacoesIndexRoute: ImportacoesIndexRoute,
}

const ImportacoesRouteWithChildren = ImportacoesRoute._addFileChildren(
  ImportacoesRouteChildren,
)

interface LogisticaRouteChildren {
  LogisticaMapaRoute: typeof LogisticaMapaRoute
  LogisticaIndexRoute: typeof LogisticaIndexRoute
}

const LogisticaRouteChildren: LogisticaRouteChildren = {
  LogisticaMapaRoute: LogisticaMapaRoute,
  LogisticaIndexRoute: LogisticaIndexRoute,
}

const LogisticaRouteWithChildren = LogisticaRoute._addFileChildren(
  LogisticaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRouteWithChildren,
  ClientesImpactoRoute: ClientesImpactoRoute,
  FinancasRoute: FinancasRoute,
  ImportacoesRoute: ImportacoesRouteWithChildren,
  LoginRoute: LoginRoute,
  LogisticaRoute: LogisticaRouteWithChildren,
  ProcessamentosRoute: ProcessamentosRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  SimulacaoRoute: SimulacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
