using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InovaSkill.Importer.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ImportDbContext))]
[Migration("202608010001_AddAiConsumptionManagement")]
public sealed class AddAiConsumptionManagement : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            CREATE TABLE ai_consumption_settings (
                "Id" integer PRIMARY KEY,
                "Model" varchar(128) NOT NULL,
                "DefaultMonthlyTokenLimit" bigint NOT NULL,
                "DefaultAlertPercentage" numeric(5,2) NOT NULL,
                "UpdatedAt" timestamptz NOT NULL
            );
            CREATE TABLE ai_model_prices (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Model" varchar(128) NOT NULL,
                "InputPricePerMillionUsd" numeric(18,8) NOT NULL,
                "OutputPricePerMillionUsd" numeric(18,8) NOT NULL,
                "EffectiveFrom" timestamptz NOT NULL,
                "CreatedAt" timestamptz NOT NULL
            );
            CREATE UNIQUE INDEX "IX_ai_model_prices_Model_EffectiveFrom" ON ai_model_prices ("Model", "EffectiveFrom");
            CREATE TABLE ai_response_executions (
                "Id" uuid PRIMARY KEY,
                "UserId" bigint NOT NULL REFERENCES app_users("Id") ON DELETE RESTRICT,
                "ChatSessionId" uuid NULL,
                "Status" varchar(32) NOT NULL,
                "CreatedAt" timestamptz NOT NULL,
                "CompletedAt" timestamptz NULL
            );
            CREATE INDEX "IX_ai_response_executions_UserId_CreatedAt" ON ai_response_executions ("UserId", "CreatedAt");
            CREATE TABLE ai_provider_calls (
                "Id" uuid PRIMARY KEY,
                "ResponseExecutionId" uuid NOT NULL REFERENCES ai_response_executions("Id") ON DELETE CASCADE,
                "ProviderResponseId" varchar(128) NOT NULL,
                "Model" varchar(128) NOT NULL,
                "Purpose" varchar(32) NOT NULL,
                "Status" varchar(32) NOT NULL,
                "InputTokens" integer NOT NULL,
                "OutputTokens" integer NOT NULL,
                "InputPricePerMillionUsd" numeric(18,8) NOT NULL,
                "OutputPricePerMillionUsd" numeric(18,8) NOT NULL,
                "InputCostUsd" numeric(18,8) NOT NULL,
                "OutputCostUsd" numeric(18,8) NOT NULL,
                "CreatedAt" timestamptz NOT NULL
            );
            CREATE INDEX "IX_ai_provider_calls_ResponseExecutionId_CreatedAt" ON ai_provider_calls ("ResponseExecutionId", "CreatedAt");
            CREATE INDEX "IX_ai_provider_calls_Model_CreatedAt" ON ai_provider_calls ("Model", "CreatedAt");
            CREATE TABLE ai_user_limits (
                "UserId" bigint PRIMARY KEY REFERENCES app_users("Id") ON DELETE CASCADE,
                "MonthlyTokenLimit" bigint NULL,
                "AlertPercentage" numeric(5,2) NULL,
                "UpdatedAt" timestamptz NOT NULL
            );
            CREATE TABLE ai_consumption_alerts (
                "Id" uuid PRIMARY KEY,
                "UserId" bigint NOT NULL REFERENCES app_users("Id") ON DELETE CASCADE,
                "PeriodMonth" date NOT NULL,
                "Level" varchar(32) NOT NULL,
                "ConsumedTokens" bigint NOT NULL,
                "TokenLimit" bigint NOT NULL,
                "CreatedAt" timestamptz NOT NULL,
                "ReadAt" timestamptz NULL
            );
            CREATE UNIQUE INDEX "IX_ai_consumption_alerts_UserId_PeriodMonth_Level" ON ai_consumption_alerts ("UserId", "PeriodMonth", "Level");
            CREATE INDEX "IX_ai_consumption_alerts_ReadAt_CreatedAt" ON ai_consumption_alerts ("ReadAt", "CreatedAt");
            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS ai_consumption_alerts;
            DROP TABLE IF EXISTS ai_user_limits;
            DROP TABLE IF EXISTS ai_provider_calls;
            DROP TABLE IF EXISTS ai_response_executions;
            DROP TABLE IF EXISTS ai_model_prices;
            DROP TABLE IF EXISTS ai_consumption_settings;
            """);
    }
}
