using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace InovaSkill.Importer.Infrastructure.Persistence.Migrations;

[DbContext(typeof(ImportDbContext))]
[Migration("202607040002_ResetApplicationForRouteImports")]
public sealed class ResetApplicationForRouteImports : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DO $$
            DECLARE table_name text;
            BEGIN
                FOR table_name IN
                    SELECT tablename
                    FROM pg_tables
                    WHERE schemaname = 'public'
                      AND tablename <> '__EFMigrationsHistory'
                LOOP
                    EXECUTE format('DROP TABLE IF EXISTS %I CASCADE', table_name);
                END LOOP;
            END $$;

            CREATE TABLE app_users (
                "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Name" varchar(256) NOT NULL UNIQUE,
                "Email" varchar(256) NOT NULL UNIQUE,
                "Role" varchar(64) NOT NULL,
                "PasswordHash" varchar(1024) NOT NULL,
                "CreatedAt" timestamptz NOT NULL
            );
            CREATE TABLE IF NOT EXISTS data_sources (
                "Id" uuid PRIMARY KEY,
                "Code" varchar(64) NOT NULL UNIQUE,
                "Name" varchar(160) NOT NULL,
                "Type" varchar(32) NOT NULL,
                "Active" boolean NOT NULL,
                "CreatedAt" timestamptz NOT NULL,
                "UpdatedAt" timestamptz NOT NULL
            );
            CREATE TABLE IF NOT EXISTS imports (
                "Id" uuid PRIMARY KEY,
                "DataSourceId" uuid NOT NULL REFERENCES data_sources("Id"),
                "FileName" varchar(512) NOT NULL,
                "FilePath" varchar(1024) NOT NULL,
                "Status" varchar(32) NOT NULL,
                "TotalRows" integer NOT NULL,
                "ImportedRows" integer NOT NULL,
                "ErrorCount" integer NOT NULL,
                "FailureMessage" varchar(1024),
                "CreatedAt" timestamptz NOT NULL,
                "StartedAt" timestamptz,
                "FinishedAt" timestamptz
            );
            CREATE TABLE IF NOT EXISTS import_errors (
                "Id" uuid PRIMARY KEY,
                "ImportId" uuid NOT NULL REFERENCES imports("Id") ON DELETE CASCADE,
                "SheetName" varchar(128) NOT NULL,
                "RowNumber" integer NOT NULL,
                "Field" varchar(64) NOT NULL,
                "RawValue" varchar(512) NOT NULL,
                "Message" varchar(1024) NOT NULL,
                "Status" varchar(16) NOT NULL,
                "CorrectedValue" varchar(512),
                "CreatedAt" timestamptz NOT NULL,
                "ResolvedAt" timestamptz
            );
            CREATE TABLE IF NOT EXISTS job_executions (
                "Id" uuid PRIMARY KEY,
                "JobType" varchar(64) NOT NULL,
                "Status" varchar(32) NOT NULL,
                "RelatedEntityId" uuid NOT NULL REFERENCES imports("Id") ON DELETE CASCADE,
                "Attempts" integer NOT NULL,
                "CreatedAt" timestamptz NOT NULL,
                "StartedAt" timestamptz,
                "FinishedAt" timestamptz,
                "ErrorMessage" varchar(1024)
            );
            CREATE TABLE IF NOT EXISTS vehicle_types (
                "Id" uuid PRIMARY KEY,
                "Name" varchar(64) NOT NULL UNIQUE,
                "CapacityKg" numeric(12,2) NOT NULL
            );
            CREATE TABLE IF NOT EXISTS routes (
                "Id" uuid PRIMARY KEY,
                "ImportId" uuid NOT NULL REFERENCES imports("Id") ON DELETE CASCADE,
                "Name" varchar(256) NOT NULL,
                "Weekday" varchar(16) NOT NULL,
                "VehicleTypeId" uuid NOT NULL REFERENCES vehicle_types("Id"),
                "CreatedAt" timestamptz NOT NULL
            );
            CREATE TABLE IF NOT EXISTS route_entries (
                "Id" uuid PRIMARY KEY,
                "RouteId" uuid NOT NULL REFERENCES routes("Id") ON DELETE CASCADE,
                "Sequence" integer NOT NULL,
                "Name" varchar(256) NOT NULL,
                "Deliveries" integer NOT NULL,
                "AveragePerDay" numeric(18,2) NOT NULL,
                "Note" varchar(2000),
                "CreatedAt" timestamptz NOT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_imports_Status_CreatedAt" ON imports ("Status", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "IX_import_errors_ImportId_Status" ON import_errors ("ImportId", "Status");
            CREATE INDEX IF NOT EXISTS "IX_job_executions_Status_CreatedAt" ON job_executions ("Status", "CreatedAt");
            CREATE INDEX IF NOT EXISTS "IX_routes_ImportId_Weekday_Name" ON routes ("ImportId", "Weekday", "Name");
            CREATE INDEX IF NOT EXISTS "IX_route_entries_RouteId_Sequence" ON route_entries ("RouteId", "Sequence");
            INSERT INTO data_sources ("Id", "Code", "Name", "Type", "Active", "CreatedAt", "UpdatedAt")
            VALUES ('8ef15592-cd6f-4a15-afe8-b750dcbb42a7', 'ROUTES_BY_CITY', 'Rotas por Cidades', 'EXCEL', true, now(), now())
            ON CONFLICT ("Code") DO NOTHING;

            """);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql("""
            DROP TABLE IF EXISTS route_entries;
            DROP TABLE IF EXISTS routes;
            DROP TABLE IF EXISTS vehicle_types;
            DROP TABLE IF EXISTS job_executions;
            DROP TABLE IF EXISTS import_errors;
            DROP TABLE IF EXISTS imports;
            DROP TABLE IF EXISTS data_sources;
            DROP TABLE IF EXISTS app_users;
            """);
    }
}
